version: '3.8'

services:
  dynsyn:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: dynsyn-training
    
    # GPU support (if needed)
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    
    # Environment variables
    environment:
      - MUJOCO_GL=egl
      - CUDA_VISIBLE_DEVICES=0
      - WANDB_API_KEY=${WANDB_API_KEY:-}
    
    # Volume mounts
    volumes:
      - ./logs:/app/logs
      - ./configs:/app/configs
      - ./results:/app/results
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    
    # Network settings
    network_mode: "host"
    
    # Resource limits
    mem_limit: 16g
    shm_size: 2g
    
    # Restart policy
    restart: unless-stopped
    
    # Working directory
    working_dir: /app
    
    # Interactive terminal
    stdin_open: true
    tty: true

  # Optional: Jupyter development environment
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: dynsyn-jupyter
    
    command: jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root
    
    ports:
      - "8888:8888"
    
    volumes:
      - .:/app
      - ./logs:/app/logs
    
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=dynsyn123
    
    profiles:
      - dev

# Network configuration
networks:
  default:
    driver: bridge

# Volumes
volumes:
  logs:
  results: 