version: '3.8'

services:
  dynsyn:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: dynsyn-training
    
    # GPU 支持（如果需要）
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    
    # 环境变量
    environment:
      - MUJOCO_GL=egl
      - CUDA_VISIBLE_DEVICES=0
      - WANDB_API_KEY=${WANDB_API_KEY:-}
    
    # 数据卷挂载
    volumes:
      - ./logs:/app/logs
      - ./configs:/app/configs
      - ./results:/app/results
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    
    # 网络设置
    network_mode: "host"
    
    # 资源限制
    mem_limit: 16g
    shm_size: 2g
    
    # 重启策略
    restart: unless-stopped
    
    # 工作目录
    working_dir: /app
    
    # 交互式终端
    stdin_open: true
    tty: true

  # 可选：Jupyter 开发环境
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: dynsyn-jupyter
    
    command: jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root
    
    ports:
      - "8888:8888"
    
    volumes:
      - .:/app
      - ./logs:/app/logs
    
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=dynsyn123
    
    profiles:
      - dev

# 网络配置
networks:
  default:
    driver: bridge

# 数据卷
volumes:
  logs:
  results: 